package com.sicoms.smartplug.dao;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig dbSettingVoDaoConfig;
    private final DaoConfig dbPhoneVoDaoConfig;
    private final DaoConfig dbGroupVoDaoConfig;
    private final DaoConfig dbGroupSettingVoDaoConfig;
    private final DaoConfig dbPlaceVoDaoConfig;
    private final DaoConfig dbPlaceSettingVoDaoConfig;
    private final DaoConfig dbUserVoDaoConfig;
    private final DaoConfig dbPlugVoDaoConfig;
    private final DaoConfig dbLastDataVoDaoConfig;
    private final DaoConfig dbCutOffVoDaoConfig;
    private final DaoConfig dbScheduleVoDaoConfig;
    private final DaoConfig dbApVoDaoConfig;
    private final DaoConfig dbRouterVoDaoConfig;
    private final DaoConfig dbGatewayVoDaoConfig;
    private final DaoConfig dbBluetoothVoDaoConfig;
    private final DaoConfig dbGroupPlugMappingVoDaoConfig;
    private final DaoConfig dbGroupUserMappingVoDaoConfig;

    private final DbSettingVoDao dbSettingVoDao;
    private final DbPhoneVoDao dbPhoneVoDao;
    private final DbGroupVoDao dbGroupVoDao;
    private final DbGroupSettingVoDao dbGroupSettingVoDao;
    private final DbPlaceVoDao dbPlaceVoDao;
    private final DbPlaceSettingVoDao dbPlaceSettingVoDao;
    private final DbUserVoDao dbUserVoDao;
    private final DbPlugVoDao dbPlugVoDao;
    private final DbLastDataVoDao dbLastDataVoDao;
    private final DbCutOffVoDao dbCutOffVoDao;
    private final DbScheduleVoDao dbScheduleVoDao;
    private final DbApVoDao dbApVoDao;
    private final DbRouterVoDao dbRouterVoDao;
    private final DbGatewayVoDao dbGatewayVoDao;
    private final DbBluetoothVoDao dbBluetoothVoDao;
    private final DbGroupPlugMappingVoDao dbGroupPlugMappingVoDao;
    private final DbGroupUserMappingVoDao dbGroupUserMappingVoDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        dbSettingVoDaoConfig = daoConfigMap.get(DbSettingVoDao.class).clone();
        dbSettingVoDaoConfig.initIdentityScope(type);

        dbPhoneVoDaoConfig = daoConfigMap.get(DbPhoneVoDao.class).clone();
        dbPhoneVoDaoConfig.initIdentityScope(type);

        dbGroupVoDaoConfig = daoConfigMap.get(DbGroupVoDao.class).clone();
        dbGroupVoDaoConfig.initIdentityScope(type);

        dbGroupSettingVoDaoConfig = daoConfigMap.get(DbGroupSettingVoDao.class).clone();
        dbGroupSettingVoDaoConfig.initIdentityScope(type);

        dbPlaceVoDaoConfig = daoConfigMap.get(DbPlaceVoDao.class).clone();
        dbPlaceVoDaoConfig.initIdentityScope(type);

        dbPlaceSettingVoDaoConfig = daoConfigMap.get(DbPlaceSettingVoDao.class).clone();
        dbPlaceSettingVoDaoConfig.initIdentityScope(type);

        dbUserVoDaoConfig = daoConfigMap.get(DbUserVoDao.class).clone();
        dbUserVoDaoConfig.initIdentityScope(type);

        dbPlugVoDaoConfig = daoConfigMap.get(DbPlugVoDao.class).clone();
        dbPlugVoDaoConfig.initIdentityScope(type);

        dbLastDataVoDaoConfig = daoConfigMap.get(DbLastDataVoDao.class).clone();
        dbLastDataVoDaoConfig.initIdentityScope(type);

        dbCutOffVoDaoConfig = daoConfigMap.get(DbCutOffVoDao.class).clone();
        dbCutOffVoDaoConfig.initIdentityScope(type);

        dbScheduleVoDaoConfig = daoConfigMap.get(DbScheduleVoDao.class).clone();
        dbScheduleVoDaoConfig.initIdentityScope(type);

        dbApVoDaoConfig = daoConfigMap.get(DbApVoDao.class).clone();
        dbApVoDaoConfig.initIdentityScope(type);

        dbRouterVoDaoConfig = daoConfigMap.get(DbRouterVoDao.class).clone();
        dbRouterVoDaoConfig.initIdentityScope(type);

        dbGatewayVoDaoConfig = daoConfigMap.get(DbGatewayVoDao.class).clone();
        dbGatewayVoDaoConfig.initIdentityScope(type);

        dbBluetoothVoDaoConfig = daoConfigMap.get(DbBluetoothVoDao.class).clone();
        dbBluetoothVoDaoConfig.initIdentityScope(type);

        dbGroupPlugMappingVoDaoConfig = daoConfigMap.get(DbGroupPlugMappingVoDao.class).clone();
        dbGroupPlugMappingVoDaoConfig.initIdentityScope(type);

        dbGroupUserMappingVoDaoConfig = daoConfigMap.get(DbGroupUserMappingVoDao.class).clone();
        dbGroupUserMappingVoDaoConfig.initIdentityScope(type);

        dbSettingVoDao = new DbSettingVoDao(dbSettingVoDaoConfig, this);
        dbPhoneVoDao = new DbPhoneVoDao(dbPhoneVoDaoConfig, this);
        dbGroupVoDao = new DbGroupVoDao(dbGroupVoDaoConfig, this);
        dbGroupSettingVoDao = new DbGroupSettingVoDao(dbGroupSettingVoDaoConfig, this);
        dbPlaceVoDao = new DbPlaceVoDao(dbPlaceVoDaoConfig, this);
        dbPlaceSettingVoDao = new DbPlaceSettingVoDao(dbPlaceSettingVoDaoConfig, this);
        dbUserVoDao = new DbUserVoDao(dbUserVoDaoConfig, this);
        dbPlugVoDao = new DbPlugVoDao(dbPlugVoDaoConfig, this);
        dbLastDataVoDao = new DbLastDataVoDao(dbLastDataVoDaoConfig, this);
        dbCutOffVoDao = new DbCutOffVoDao(dbCutOffVoDaoConfig, this);
        dbScheduleVoDao = new DbScheduleVoDao(dbScheduleVoDaoConfig, this);
        dbApVoDao = new DbApVoDao(dbApVoDaoConfig, this);
        dbRouterVoDao = new DbRouterVoDao(dbRouterVoDaoConfig, this);
        dbGatewayVoDao = new DbGatewayVoDao(dbGatewayVoDaoConfig, this);
        dbBluetoothVoDao = new DbBluetoothVoDao(dbBluetoothVoDaoConfig, this);
        dbGroupPlugMappingVoDao = new DbGroupPlugMappingVoDao(dbGroupPlugMappingVoDaoConfig, this);
        dbGroupUserMappingVoDao = new DbGroupUserMappingVoDao(dbGroupUserMappingVoDaoConfig, this);

        registerDao(DbSettingVo.class, dbSettingVoDao);
        registerDao(DbPhoneVo.class, dbPhoneVoDao);
        registerDao(DbGroupVo.class, dbGroupVoDao);
        registerDao(DbGroupSettingVo.class, dbGroupSettingVoDao);
        registerDao(DbPlaceVo.class, dbPlaceVoDao);
        registerDao(DbPlaceSettingVo.class, dbPlaceSettingVoDao);
        registerDao(DbUserVo.class, dbUserVoDao);
        registerDao(DbPlugVo.class, dbPlugVoDao);
        registerDao(DbLastDataVo.class, dbLastDataVoDao);
        registerDao(DbCutOffVo.class, dbCutOffVoDao);
        registerDao(DbScheduleVo.class, dbScheduleVoDao);
        registerDao(DbApVo.class, dbApVoDao);
        registerDao(DbRouterVo.class, dbRouterVoDao);
        registerDao(DbGatewayVo.class, dbGatewayVoDao);
        registerDao(DbBluetoothVo.class, dbBluetoothVoDao);
        registerDao(DbGroupPlugMappingVo.class, dbGroupPlugMappingVoDao);
        registerDao(DbGroupUserMappingVo.class, dbGroupUserMappingVoDao);
    }
    
    public void clear() {
        dbSettingVoDaoConfig.getIdentityScope().clear();
        dbPhoneVoDaoConfig.getIdentityScope().clear();
        dbGroupVoDaoConfig.getIdentityScope().clear();
        dbGroupSettingVoDaoConfig.getIdentityScope().clear();
        dbPlaceVoDaoConfig.getIdentityScope().clear();
        dbPlaceSettingVoDaoConfig.getIdentityScope().clear();
        dbUserVoDaoConfig.getIdentityScope().clear();
        dbPlugVoDaoConfig.getIdentityScope().clear();
        dbLastDataVoDaoConfig.getIdentityScope().clear();
        dbCutOffVoDaoConfig.getIdentityScope().clear();
        dbScheduleVoDaoConfig.getIdentityScope().clear();
        dbApVoDaoConfig.getIdentityScope().clear();
        dbRouterVoDaoConfig.getIdentityScope().clear();
        dbGatewayVoDaoConfig.getIdentityScope().clear();
        dbBluetoothVoDaoConfig.getIdentityScope().clear();
        dbGroupPlugMappingVoDaoConfig.getIdentityScope().clear();
        dbGroupUserMappingVoDaoConfig.getIdentityScope().clear();
    }

    public DbSettingVoDao getDbSettingVoDao() {
        return dbSettingVoDao;
    }

    public DbPhoneVoDao getDbPhoneVoDao() {
        return dbPhoneVoDao;
    }

    public DbGroupVoDao getDbGroupVoDao() {
        return dbGroupVoDao;
    }

    public DbGroupSettingVoDao getDbGroupSettingVoDao() {
        return dbGroupSettingVoDao;
    }

    public DbPlaceVoDao getDbPlaceVoDao() {
        return dbPlaceVoDao;
    }

    public DbPlaceSettingVoDao getDbPlaceSettingVoDao() {
        return dbPlaceSettingVoDao;
    }

    public DbUserVoDao getDbUserVoDao() {
        return dbUserVoDao;
    }

    public DbPlugVoDao getDbPlugVoDao() {
        return dbPlugVoDao;
    }

    public DbLastDataVoDao getDbLastDataVoDao() {
        return dbLastDataVoDao;
    }

    public DbCutOffVoDao getDbCutOffVoDao() {
        return dbCutOffVoDao;
    }

    public DbScheduleVoDao getDbScheduleVoDao() {
        return dbScheduleVoDao;
    }

    public DbApVoDao getDbApVoDao() {
        return dbApVoDao;
    }

    public DbRouterVoDao getDbRouterVoDao() {
        return dbRouterVoDao;
    }

    public DbGatewayVoDao getDbGatewayVoDao() {
        return dbGatewayVoDao;
    }

    public DbBluetoothVoDao getDbBluetoothVoDao() {
        return dbBluetoothVoDao;
    }

    public DbGroupPlugMappingVoDao getDbGroupPlugMappingVoDao() {
        return dbGroupPlugMappingVoDao;
    }

    public DbGroupUserMappingVoDao getDbGroupUserMappingVoDao() {
        return dbGroupUserMappingVoDao;
    }

}
