package com.sicoms.smartplug.dao;

import java.util.List;
import java.util.ArrayList;
import android.database.Cursor;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteStatement;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.Property;
import de.greenrobot.dao.internal.SqlUtils;
import de.greenrobot.dao.internal.DaoConfig;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table tb_ap.
*/
public class DbApVoDao extends AbstractDao<DbApVo, String> {

    public static final String TABLENAME = "tb_ap";

    /**
     * Properties of entity DbApVo.<br/>
     * Can be used for QueryBuilder and for referencing column names.
    */
    public static class Properties {
        public final static Property BssId = new Property(0, String.class, "bssId", true, "BSS_ID");
        public final static Property SsId = new Property(1, String.class, "ssId", false, "SS_ID");
        public final static Property Password = new Property(2, String.class, "password", false, "PASSWORD");
    }

    private DaoSession daoSession;


    public DbApVoDao(DaoConfig config) {
        super(config);
    }
    
    public DbApVoDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
        this.daoSession = daoSession;
    }

    /** Creates the underlying database table. */
    public static void createTable(SQLiteDatabase db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "'tb_ap' (" + //
                "'BSS_ID' TEXT PRIMARY KEY NOT NULL ," + // 0: bssId
                "'SS_ID' TEXT NOT NULL ," + // 1: ssId
                "'PASSWORD' TEXT NOT NULL );"); // 2: password
    }

    /** Drops the underlying database table. */
    public static void dropTable(SQLiteDatabase db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "'tb_ap'";
        db.execSQL(sql);
    }

    /** @inheritdoc */
    @Override
    protected void bindValues(SQLiteStatement stmt, DbApVo entity) {
        stmt.clearBindings();
 
        String bssId = entity.getBssId();
        if (bssId != null) {
            stmt.bindString(1, bssId);
        }
        stmt.bindString(2, entity.getSsId());
        stmt.bindString(3, entity.getPassword());
    }

    @Override
    protected void attachEntity(DbApVo entity) {
        super.attachEntity(entity);
        entity.__setDaoSession(daoSession);
    }

    /** @inheritdoc */
    @Override
    public String readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getString(offset + 0);
    }    

    /** @inheritdoc */
    @Override
    public DbApVo readEntity(Cursor cursor, int offset) {
        DbApVo entity = new DbApVo( //
            cursor.isNull(offset + 0) ? null : cursor.getString(offset + 0), // bssId
            cursor.getString(offset + 1), // ssId
            cursor.getString(offset + 2) // password
        );
        return entity;
    }
     
    /** @inheritdoc */
    @Override
    public void readEntity(Cursor cursor, DbApVo entity, int offset) {
        entity.setBssId(cursor.isNull(offset + 0) ? null : cursor.getString(offset + 0));
        entity.setSsId(cursor.getString(offset + 1));
        entity.setPassword(cursor.getString(offset + 2));
     }
    
    /** @inheritdoc */
    @Override
    protected String updateKeyAfterInsert(DbApVo entity, long rowId) {
        return entity.getBssId();
    }
    
    /** @inheritdoc */
    @Override
    public String getKey(DbApVo entity) {
        if(entity != null) {
            return entity.getBssId();
        } else {
            return null;
        }
    }

    /** @inheritdoc */
    @Override    
    protected boolean isEntityUpdateable() {
        return true;
    }
    
    private String selectDeep;

    protected String getSelectDeep() {
        if (selectDeep == null) {
            StringBuilder builder = new StringBuilder("SELECT ");
            SqlUtils.appendColumns(builder, "T", getAllColumns());
            builder.append(',');
            SqlUtils.appendColumns(builder, "T0", daoSession.getDbPlugVoDao().getAllColumns());
            builder.append(" FROM tb_ap T");
            builder.append(" LEFT JOIN tb_plug T0 ON T.'BSS_ID'=T0.'PLUG_ID'");
            builder.append(' ');
            selectDeep = builder.toString();
        }
        return selectDeep;
    }
    
    protected DbApVo loadCurrentDeep(Cursor cursor, boolean lock) {
        DbApVo entity = loadCurrent(cursor, 0, lock);
        int offset = getAllColumns().length;

        DbPlugVo dbPlugVo = loadCurrentOther(daoSession.getDbPlugVoDao(), cursor, offset);
        entity.setDbPlugVo(dbPlugVo);

        return entity;    
    }

    public DbApVo loadDeep(Long key) {
        assertSinglePk();
        if (key == null) {
            return null;
        }

        StringBuilder builder = new StringBuilder(getSelectDeep());
        builder.append("WHERE ");
        SqlUtils.appendColumnsEqValue(builder, "T", getPkColumns());
        String sql = builder.toString();
        
        String[] keyArray = new String[] { key.toString() };
        Cursor cursor = db.rawQuery(sql, keyArray);
        
        try {
            boolean available = cursor.moveToFirst();
            if (!available) {
                return null;
            } else if (!cursor.isLast()) {
                throw new IllegalStateException("Expected unique result, but count was " + cursor.getCount());
            }
            return loadCurrentDeep(cursor, true);
        } finally {
            cursor.close();
        }
    }
    
    /** Reads all available rows from the given cursor and returns a list of new ImageTO objects. */
    public List<DbApVo> loadAllDeepFromCursor(Cursor cursor) {
        int count = cursor.getCount();
        List<DbApVo> list = new ArrayList<DbApVo>(count);
        
        if (cursor.moveToFirst()) {
            if (identityScope != null) {
                identityScope.lock();
                identityScope.reserveRoom(count);
            }
            try {
                do {
                    list.add(loadCurrentDeep(cursor, false));
                } while (cursor.moveToNext());
            } finally {
                if (identityScope != null) {
                    identityScope.unlock();
                }
            }
        }
        return list;
    }
    
    protected List<DbApVo> loadDeepAllAndCloseCursor(Cursor cursor) {
        try {
            return loadAllDeepFromCursor(cursor);
        } finally {
            cursor.close();
        }
    }
    

    /** A raw-style query where you can pass any WHERE clause and arguments. */
    public List<DbApVo> queryDeep(String where, String... selectionArg) {
        Cursor cursor = db.rawQuery(getSelectDeep() + where, selectionArg);
        return loadDeepAllAndCloseCursor(cursor);
    }
 
}
