package com.sicoms.smartplug.dao;

import java.util.List;
import java.util.ArrayList;
import android.database.Cursor;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteStatement;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.Property;
import de.greenrobot.dao.internal.SqlUtils;
import de.greenrobot.dao.internal.DaoConfig;
import de.greenrobot.dao.query.Query;
import de.greenrobot.dao.query.QueryBuilder;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table tb_cutoff.
*/
public class DbCutOffVoDao extends AbstractDao<DbCutOffVo, Long> {

    public static final String TABLENAME = "tb_cutoff";

    /**
     * Properties of entity DbCutOffVo.<br/>
     * Can be used for QueryBuilder and for referencing column names.
    */
    public static class Properties {
        public final static Property PlugId = new Property(0, String.class, "plugId", false, "PLUG_ID");
        public final static Property CutSeq = new Property(1, Long.class, "cutSeq", true, "CUT_SEQ");
        public final static Property SetWatt = new Property(2, String.class, "setWatt", false, "SET_WATT");
        public final static Property SetMin = new Property(3, String.class, "setMin", false, "SET_MIN");
        public final static Property UseYn = new Property(4, String.class, "useYn", false, "USE_YN");
    }

    private DaoSession daoSession;

    private Query<DbCutOffVo> dbPlugVo_CutOffListQuery;

    public DbCutOffVoDao(DaoConfig config) {
        super(config);
    }
    
    public DbCutOffVoDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
        this.daoSession = daoSession;
    }

    /** Creates the underlying database table. */
    public static void createTable(SQLiteDatabase db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "'tb_cutoff' (" + //
                "'PLUG_ID' TEXT NOT NULL ," + // 0: plugId
                "'CUT_SEQ' INTEGER PRIMARY KEY AUTOINCREMENT ," + // 1: cutSeq
                "'SET_WATT' TEXT NOT NULL ," + // 2: setWatt
                "'SET_MIN' TEXT NOT NULL ," + // 3: setMin
                "'USE_YN' TEXT NOT NULL );"); // 4: useYn
        // Add Indexes
        db.execSQL("CREATE UNIQUE INDEX " + constraint + "IDX_tb_cutoff_PLUG_ID_CUT_SEQ ON tb_cutoff" +
                " (PLUG_ID,CUT_SEQ);");
    }

    /** Drops the underlying database table. */
    public static void dropTable(SQLiteDatabase db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "'tb_cutoff'";
        db.execSQL(sql);
    }

    /** @inheritdoc */
    @Override
    protected void bindValues(SQLiteStatement stmt, DbCutOffVo entity) {
        stmt.clearBindings();
        stmt.bindString(1, entity.getPlugId());
 
        Long cutSeq = entity.getCutSeq();
        if (cutSeq != null) {
            stmt.bindLong(2, cutSeq);
        }
        stmt.bindString(3, entity.getSetWatt());
        stmt.bindString(4, entity.getSetMin());
        stmt.bindString(5, entity.getUseYn());
    }

    @Override
    protected void attachEntity(DbCutOffVo entity) {
        super.attachEntity(entity);
        entity.__setDaoSession(daoSession);
    }

    /** @inheritdoc */
    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 1) ? null : cursor.getLong(offset + 1);
    }    

    /** @inheritdoc */
    @Override
    public DbCutOffVo readEntity(Cursor cursor, int offset) {
        DbCutOffVo entity = new DbCutOffVo( //
            cursor.getString(offset + 0), // plugId
            cursor.isNull(offset + 1) ? null : cursor.getLong(offset + 1), // cutSeq
            cursor.getString(offset + 2), // setWatt
            cursor.getString(offset + 3), // setMin
            cursor.getString(offset + 4) // useYn
        );
        return entity;
    }
     
    /** @inheritdoc */
    @Override
    public void readEntity(Cursor cursor, DbCutOffVo entity, int offset) {
        entity.setPlugId(cursor.getString(offset + 0));
        entity.setCutSeq(cursor.isNull(offset + 1) ? null : cursor.getLong(offset + 1));
        entity.setSetWatt(cursor.getString(offset + 2));
        entity.setSetMin(cursor.getString(offset + 3));
        entity.setUseYn(cursor.getString(offset + 4));
     }
    
    /** @inheritdoc */
    @Override
    protected Long updateKeyAfterInsert(DbCutOffVo entity, long rowId) {
        entity.setCutSeq(rowId);
        return rowId;
    }
    
    /** @inheritdoc */
    @Override
    public Long getKey(DbCutOffVo entity) {
        if(entity != null) {
            return entity.getCutSeq();
        } else {
            return null;
        }
    }

    /** @inheritdoc */
    @Override    
    protected boolean isEntityUpdateable() {
        return true;
    }
    
    /** Internal query to resolve the "cutOffList" to-many relationship of DbPlugVo. */
    public List<DbCutOffVo> _queryDbPlugVo_CutOffList(String plugId) {
        synchronized (this) {
            if (dbPlugVo_CutOffListQuery == null) {
                QueryBuilder<DbCutOffVo> queryBuilder = queryBuilder();
                queryBuilder.where(Properties.PlugId.eq(null));
                dbPlugVo_CutOffListQuery = queryBuilder.build();
            }
        }
        Query<DbCutOffVo> query = dbPlugVo_CutOffListQuery.forCurrentThread();
        query.setParameter(0, plugId);
        return query.list();
    }

    private String selectDeep;

    protected String getSelectDeep() {
        if (selectDeep == null) {
            StringBuilder builder = new StringBuilder("SELECT ");
            SqlUtils.appendColumns(builder, "T", getAllColumns());
            builder.append(',');
            SqlUtils.appendColumns(builder, "T0", daoSession.getDbPlugVoDao().getAllColumns());
            builder.append(" FROM tb_cutoff T");
            builder.append(" LEFT JOIN tb_plug T0 ON T.'PLUG_ID'=T0.'PLUG_ID'");
            builder.append(' ');
            selectDeep = builder.toString();
        }
        return selectDeep;
    }
    
    protected DbCutOffVo loadCurrentDeep(Cursor cursor, boolean lock) {
        DbCutOffVo entity = loadCurrent(cursor, 0, lock);
        int offset = getAllColumns().length;

        DbPlugVo dbPlugVo = loadCurrentOther(daoSession.getDbPlugVoDao(), cursor, offset);
         if(dbPlugVo != null) {
            entity.setDbPlugVo(dbPlugVo);
        }

        return entity;    
    }

    public DbCutOffVo loadDeep(Long key) {
        assertSinglePk();
        if (key == null) {
            return null;
        }

        StringBuilder builder = new StringBuilder(getSelectDeep());
        builder.append("WHERE ");
        SqlUtils.appendColumnsEqValue(builder, "T", getPkColumns());
        String sql = builder.toString();
        
        String[] keyArray = new String[] { key.toString() };
        Cursor cursor = db.rawQuery(sql, keyArray);
        
        try {
            boolean available = cursor.moveToFirst();
            if (!available) {
                return null;
            } else if (!cursor.isLast()) {
                throw new IllegalStateException("Expected unique result, but count was " + cursor.getCount());
            }
            return loadCurrentDeep(cursor, true);
        } finally {
            cursor.close();
        }
    }
    
    /** Reads all available rows from the given cursor and returns a list of new ImageTO objects. */
    public List<DbCutOffVo> loadAllDeepFromCursor(Cursor cursor) {
        int count = cursor.getCount();
        List<DbCutOffVo> list = new ArrayList<DbCutOffVo>(count);
        
        if (cursor.moveToFirst()) {
            if (identityScope != null) {
                identityScope.lock();
                identityScope.reserveRoom(count);
            }
            try {
                do {
                    list.add(loadCurrentDeep(cursor, false));
                } while (cursor.moveToNext());
            } finally {
                if (identityScope != null) {
                    identityScope.unlock();
                }
            }
        }
        return list;
    }
    
    protected List<DbCutOffVo> loadDeepAllAndCloseCursor(Cursor cursor) {
        try {
            return loadAllDeepFromCursor(cursor);
        } finally {
            cursor.close();
        }
    }
    

    /** A raw-style query where you can pass any WHERE clause and arguments. */
    public List<DbCutOffVo> queryDeep(String where, String... selectionArg) {
        Cursor cursor = db.rawQuery(getSelectDeep() + where, selectionArg);
        return loadDeepAllAndCloseCursor(cursor);
    }
 
}
