package com.sicoms.smartplug.dao;

import java.util.List;
import java.util.ArrayList;
import android.database.Cursor;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteStatement;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.Property;
import de.greenrobot.dao.internal.SqlUtils;
import de.greenrobot.dao.internal.DaoConfig;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table tb_gateway.
*/
public class DbGatewayVoDao extends AbstractDao<DbGatewayVo, String> {

    public static final String TABLENAME = "tb_gateway";

    /**
     * Properties of entity DbGatewayVo.<br/>
     * Can be used for QueryBuilder and for referencing column names.
    */
    public static class Properties {
        public final static Property GatewayIp = new Property(0, String.class, "gatewayIp", true, "GATEWAY_IP");
        public final static Property SsId = new Property(1, String.class, "ssId", false, "SS_ID");
    }

    private DaoSession daoSession;


    public DbGatewayVoDao(DaoConfig config) {
        super(config);
    }
    
    public DbGatewayVoDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
        this.daoSession = daoSession;
    }

    /** Creates the underlying database table. */
    public static void createTable(SQLiteDatabase db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "'tb_gateway' (" + //
                "'GATEWAY_IP' TEXT PRIMARY KEY NOT NULL ," + // 0: gatewayIp
                "'SS_ID' TEXT NOT NULL );"); // 1: ssId
    }

    /** Drops the underlying database table. */
    public static void dropTable(SQLiteDatabase db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "'tb_gateway'";
        db.execSQL(sql);
    }

    /** @inheritdoc */
    @Override
    protected void bindValues(SQLiteStatement stmt, DbGatewayVo entity) {
        stmt.clearBindings();
 
        String gatewayIp = entity.getGatewayIp();
        if (gatewayIp != null) {
            stmt.bindString(1, gatewayIp);
        }
        stmt.bindString(2, entity.getSsId());
    }

    @Override
    protected void attachEntity(DbGatewayVo entity) {
        super.attachEntity(entity);
        entity.__setDaoSession(daoSession);
    }

    /** @inheritdoc */
    @Override
    public String readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getString(offset + 0);
    }    

    /** @inheritdoc */
    @Override
    public DbGatewayVo readEntity(Cursor cursor, int offset) {
        DbGatewayVo entity = new DbGatewayVo( //
            cursor.isNull(offset + 0) ? null : cursor.getString(offset + 0), // gatewayIp
            cursor.getString(offset + 1) // ssId
        );
        return entity;
    }
     
    /** @inheritdoc */
    @Override
    public void readEntity(Cursor cursor, DbGatewayVo entity, int offset) {
        entity.setGatewayIp(cursor.isNull(offset + 0) ? null : cursor.getString(offset + 0));
        entity.setSsId(cursor.getString(offset + 1));
     }
    
    /** @inheritdoc */
    @Override
    protected String updateKeyAfterInsert(DbGatewayVo entity, long rowId) {
        return entity.getGatewayIp();
    }
    
    /** @inheritdoc */
    @Override
    public String getKey(DbGatewayVo entity) {
        if(entity != null) {
            return entity.getGatewayIp();
        } else {
            return null;
        }
    }

    /** @inheritdoc */
    @Override    
    protected boolean isEntityUpdateable() {
        return true;
    }
    
    private String selectDeep;

    protected String getSelectDeep() {
        if (selectDeep == null) {
            StringBuilder builder = new StringBuilder("SELECT ");
            SqlUtils.appendColumns(builder, "T", getAllColumns());
            builder.append(',');
            SqlUtils.appendColumns(builder, "T0", daoSession.getDbPlugVoDao().getAllColumns());
            builder.append(" FROM tb_gateway T");
            builder.append(" LEFT JOIN tb_plug T0 ON T.'GATEWAY_IP'=T0.'PLUG_ID'");
            builder.append(' ');
            selectDeep = builder.toString();
        }
        return selectDeep;
    }
    
    protected DbGatewayVo loadCurrentDeep(Cursor cursor, boolean lock) {
        DbGatewayVo entity = loadCurrent(cursor, 0, lock);
        int offset = getAllColumns().length;

        DbPlugVo dbPlugVo = loadCurrentOther(daoSession.getDbPlugVoDao(), cursor, offset);
        entity.setDbPlugVo(dbPlugVo);

        return entity;    
    }

    public DbGatewayVo loadDeep(Long key) {
        assertSinglePk();
        if (key == null) {
            return null;
        }

        StringBuilder builder = new StringBuilder(getSelectDeep());
        builder.append("WHERE ");
        SqlUtils.appendColumnsEqValue(builder, "T", getPkColumns());
        String sql = builder.toString();
        
        String[] keyArray = new String[] { key.toString() };
        Cursor cursor = db.rawQuery(sql, keyArray);
        
        try {
            boolean available = cursor.moveToFirst();
            if (!available) {
                return null;
            } else if (!cursor.isLast()) {
                throw new IllegalStateException("Expected unique result, but count was " + cursor.getCount());
            }
            return loadCurrentDeep(cursor, true);
        } finally {
            cursor.close();
        }
    }
    
    /** Reads all available rows from the given cursor and returns a list of new ImageTO objects. */
    public List<DbGatewayVo> loadAllDeepFromCursor(Cursor cursor) {
        int count = cursor.getCount();
        List<DbGatewayVo> list = new ArrayList<DbGatewayVo>(count);
        
        if (cursor.moveToFirst()) {
            if (identityScope != null) {
                identityScope.lock();
                identityScope.reserveRoom(count);
            }
            try {
                do {
                    list.add(loadCurrentDeep(cursor, false));
                } while (cursor.moveToNext());
            } finally {
                if (identityScope != null) {
                    identityScope.unlock();
                }
            }
        }
        return list;
    }
    
    protected List<DbGatewayVo> loadDeepAllAndCloseCursor(Cursor cursor) {
        try {
            return loadAllDeepFromCursor(cursor);
        } finally {
            cursor.close();
        }
    }
    

    /** A raw-style query where you can pass any WHERE clause and arguments. */
    public List<DbGatewayVo> queryDeep(String where, String... selectionArg) {
        Cursor cursor = db.rawQuery(getSelectDeep() + where, selectionArg);
        return loadDeepAllAndCloseCursor(cursor);
    }
 
}
