package com.sicoms.smartplug.dao;

import java.util.List;
import java.util.ArrayList;
import android.database.Cursor;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteStatement;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.Property;
import de.greenrobot.dao.internal.SqlUtils;
import de.greenrobot.dao.internal.DaoConfig;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table tb_group_plug_mapping.
*/
public class DbGroupPlugMappingVoDao extends AbstractDao<DbGroupPlugMappingVo, Long> {

    public static final String TABLENAME = "tb_group_plug_mapping";

    /**
     * Properties of entity DbGroupPlugMappingVo.<br/>
     * Can be used for QueryBuilder and for referencing column names.
    */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property GroupId = new Property(1, long.class, "groupId", false, "GROUP_ID");
        public final static Property PlugId = new Property(2, String.class, "plugId", false, "PLUG_ID");
        public final static Property Wh = new Property(3, float.class, "wh", false, "WH");
    }

    private DaoSession daoSession;


    public DbGroupPlugMappingVoDao(DaoConfig config) {
        super(config);
    }
    
    public DbGroupPlugMappingVoDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
        this.daoSession = daoSession;
    }

    /** Creates the underlying database table. */
    public static void createTable(SQLiteDatabase db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "'tb_group_plug_mapping' (" + //
                "'_id' INTEGER PRIMARY KEY AUTOINCREMENT ," + // 0: id
                "'GROUP_ID' INTEGER NOT NULL ," + // 1: groupId
                "'PLUG_ID' TEXT NOT NULL ," + // 2: plugId
                "'WH' REAL NOT NULL );"); // 3: wh
        // Add Indexes
        db.execSQL("CREATE UNIQUE INDEX " + constraint + "IDX_tb_group_plug_mapping_GROUP_ID_PLUG_ID ON tb_group_plug_mapping" +
                " (GROUP_ID,PLUG_ID);");
    }

    /** Drops the underlying database table. */
    public static void dropTable(SQLiteDatabase db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "'tb_group_plug_mapping'";
        db.execSQL(sql);
    }

    /** @inheritdoc */
    @Override
    protected void bindValues(SQLiteStatement stmt, DbGroupPlugMappingVo entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
        stmt.bindLong(2, entity.getGroupId());
        stmt.bindString(3, entity.getPlugId());
        stmt.bindDouble(4, entity.getWh());
    }

    @Override
    protected void attachEntity(DbGroupPlugMappingVo entity) {
        super.attachEntity(entity);
        entity.__setDaoSession(daoSession);
    }

    /** @inheritdoc */
    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    /** @inheritdoc */
    @Override
    public DbGroupPlugMappingVo readEntity(Cursor cursor, int offset) {
        DbGroupPlugMappingVo entity = new DbGroupPlugMappingVo( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.getLong(offset + 1), // groupId
            cursor.getString(offset + 2), // plugId
            cursor.getFloat(offset + 3) // wh
        );
        return entity;
    }
     
    /** @inheritdoc */
    @Override
    public void readEntity(Cursor cursor, DbGroupPlugMappingVo entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setGroupId(cursor.getLong(offset + 1));
        entity.setPlugId(cursor.getString(offset + 2));
        entity.setWh(cursor.getFloat(offset + 3));
     }
    
    /** @inheritdoc */
    @Override
    protected Long updateKeyAfterInsert(DbGroupPlugMappingVo entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    /** @inheritdoc */
    @Override
    public Long getKey(DbGroupPlugMappingVo entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    /** @inheritdoc */
    @Override    
    protected boolean isEntityUpdateable() {
        return true;
    }
    
    private String selectDeep;

    protected String getSelectDeep() {
        if (selectDeep == null) {
            StringBuilder builder = new StringBuilder("SELECT ");
            SqlUtils.appendColumns(builder, "T", getAllColumns());
            builder.append(',');
            SqlUtils.appendColumns(builder, "T0", daoSession.getDbGroupVoDao().getAllColumns());
            builder.append(',');
            SqlUtils.appendColumns(builder, "T1", daoSession.getDbPlugVoDao().getAllColumns());
            builder.append(" FROM tb_group_plug_mapping T");
            builder.append(" LEFT JOIN tb_group T0 ON T.'GROUP_ID'=T0.'GROUP_ID'");
            builder.append(" LEFT JOIN tb_plug T1 ON T.'PLUG_ID'=T1.'PLUG_ID'");
            builder.append(' ');
            selectDeep = builder.toString();
        }
        return selectDeep;
    }
    
    protected DbGroupPlugMappingVo loadCurrentDeep(Cursor cursor, boolean lock) {
        DbGroupPlugMappingVo entity = loadCurrent(cursor, 0, lock);
        int offset = getAllColumns().length;

        DbGroupVo dbGroupVo = loadCurrentOther(daoSession.getDbGroupVoDao(), cursor, offset);
         if(dbGroupVo != null) {
            entity.setDbGroupVo(dbGroupVo);
        }
        offset += daoSession.getDbGroupVoDao().getAllColumns().length;

        DbPlugVo dbPlugVo = loadCurrentOther(daoSession.getDbPlugVoDao(), cursor, offset);
         if(dbPlugVo != null) {
            entity.setDbPlugVo(dbPlugVo);
        }

        return entity;    
    }

    public DbGroupPlugMappingVo loadDeep(Long key) {
        assertSinglePk();
        if (key == null) {
            return null;
        }

        StringBuilder builder = new StringBuilder(getSelectDeep());
        builder.append("WHERE ");
        SqlUtils.appendColumnsEqValue(builder, "T", getPkColumns());
        String sql = builder.toString();
        
        String[] keyArray = new String[] { key.toString() };
        Cursor cursor = db.rawQuery(sql, keyArray);
        
        try {
            boolean available = cursor.moveToFirst();
            if (!available) {
                return null;
            } else if (!cursor.isLast()) {
                throw new IllegalStateException("Expected unique result, but count was " + cursor.getCount());
            }
            return loadCurrentDeep(cursor, true);
        } finally {
            cursor.close();
        }
    }
    
    /** Reads all available rows from the given cursor and returns a list of new ImageTO objects. */
    public List<DbGroupPlugMappingVo> loadAllDeepFromCursor(Cursor cursor) {
        int count = cursor.getCount();
        List<DbGroupPlugMappingVo> list = new ArrayList<DbGroupPlugMappingVo>(count);
        
        if (cursor.moveToFirst()) {
            if (identityScope != null) {
                identityScope.lock();
                identityScope.reserveRoom(count);
            }
            try {
                do {
                    list.add(loadCurrentDeep(cursor, false));
                } while (cursor.moveToNext());
            } finally {
                if (identityScope != null) {
                    identityScope.unlock();
                }
            }
        }
        return list;
    }
    
    protected List<DbGroupPlugMappingVo> loadDeepAllAndCloseCursor(Cursor cursor) {
        try {
            return loadAllDeepFromCursor(cursor);
        } finally {
            cursor.close();
        }
    }
    

    /** A raw-style query where you can pass any WHERE clause and arguments. */
    public List<DbGroupPlugMappingVo> queryDeep(String where, String... selectionArg) {
        Cursor cursor = db.rawQuery(getSelectDeep() + where, selectionArg);
        return loadDeepAllAndCloseCursor(cursor);
    }
 
}
