package com.sicoms.smartplug.dao;

import de.greenrobot.dao.DaoException;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table tb_group_user_mapping.
 */
public class DbGroupUserMappingVo {

    private Long id;
    private long groupId;
    /** Not-null value. */
    private String userId;
    /** Not-null value. */
    private String auth;

    /** Used to resolve relations */
    private transient DaoSession daoSession;

    /** Used for active entity operations. */
    private transient DbGroupUserMappingVoDao myDao;

    private DbGroupVo dbGroupVo;
    private Long dbGroupVo__resolvedKey;

    private DbUserVo dbUserVo;
    private String dbUserVo__resolvedKey;


    public DbGroupUserMappingVo() {
    }

    public DbGroupUserMappingVo(Long id) {
        this.id = id;
    }

    public DbGroupUserMappingVo(Long id, long groupId, String userId, String auth) {
        this.id = id;
        this.groupId = groupId;
        this.userId = userId;
        this.auth = auth;
    }

    /** called by internal mechanisms, do not call yourself. */
    public void __setDaoSession(DaoSession daoSession) {
        this.daoSession = daoSession;
        myDao = daoSession != null ? daoSession.getDbGroupUserMappingVoDao() : null;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public long getGroupId() {
        return groupId;
    }

    public void setGroupId(long groupId) {
        this.groupId = groupId;
    }

    /** Not-null value. */
    public String getUserId() {
        return userId;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setUserId(String userId) {
        this.userId = userId;
    }

    /** Not-null value. */
    public String getAuth() {
        return auth;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setAuth(String auth) {
        this.auth = auth;
    }

    /** To-one relationship, resolved on first access. */
    public DbGroupVo getDbGroupVo() {
        long __key = this.groupId;
        if (dbGroupVo__resolvedKey == null || !dbGroupVo__resolvedKey.equals(__key)) {
            if (daoSession == null) {
                throw new DaoException("Entity is detached from DAO context");
            }
            DbGroupVoDao targetDao = daoSession.getDbGroupVoDao();
            DbGroupVo dbGroupVoNew = targetDao.load(__key);
            synchronized (this) {
                dbGroupVo = dbGroupVoNew;
            	dbGroupVo__resolvedKey = __key;
            }
        }
        return dbGroupVo;
    }

    public void setDbGroupVo(DbGroupVo dbGroupVo) {
        if (dbGroupVo == null) {
            throw new DaoException("To-one property 'groupId' has not-null constraint; cannot set to-one to null");
        }
        synchronized (this) {
            this.dbGroupVo = dbGroupVo;
            groupId = dbGroupVo.getGroupId();
            dbGroupVo__resolvedKey = groupId;
        }
    }

    /** To-one relationship, resolved on first access. */
    public DbUserVo getDbUserVo() {
        String __key = this.userId;
        if (dbUserVo__resolvedKey == null || dbUserVo__resolvedKey != __key) {
            if (daoSession == null) {
                throw new DaoException("Entity is detached from DAO context");
            }
            DbUserVoDao targetDao = daoSession.getDbUserVoDao();
            DbUserVo dbUserVoNew = targetDao.load(__key);
            synchronized (this) {
                dbUserVo = dbUserVoNew;
            	dbUserVo__resolvedKey = __key;
            }
        }
        return dbUserVo;
    }

    public void setDbUserVo(DbUserVo dbUserVo) {
        if (dbUserVo == null) {
            throw new DaoException("To-one property 'userId' has not-null constraint; cannot set to-one to null");
        }
        synchronized (this) {
            this.dbUserVo = dbUserVo;
            userId = dbUserVo.getUserId();
            dbUserVo__resolvedKey = userId;
        }
    }

    /** Convenient call for {@link AbstractDao#delete(Object)}. Entity must attached to an entity context. */
    public void delete() {
        if (myDao == null) {
            throw new DaoException("Entity is detached from DAO context");
        }    
        myDao.delete(this);
    }

    /** Convenient call for {@link AbstractDao#update(Object)}. Entity must attached to an entity context. */
    public void update() {
        if (myDao == null) {
            throw new DaoException("Entity is detached from DAO context");
        }    
        myDao.update(this);
    }

    /** Convenient call for {@link AbstractDao#refresh(Object)}. Entity must attached to an entity context. */
    public void refresh() {
        if (myDao == null) {
            throw new DaoException("Entity is detached from DAO context");
        }    
        myDao.refresh(this);
    }

}
