package com.sicoms.smartplug.dao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table tb_phone.
 */
public class DbPhoneVo {

    private String userId;
    /** Not-null value. */
    private String userName;
    private String profileImg;

    public DbPhoneVo() {
    }

    public DbPhoneVo(String userId) {
        this.userId = userId;
    }

    public DbPhoneVo(String userId, String userName, String profileImg) {
        this.userId = userId;
        this.userName = userName;
        this.profileImg = profileImg;
    }

    public String getUserId() {
        return userId;
    }

    public void setUserId(String userId) {
        this.userId = userId;
    }

    /** Not-null value. */
    public String getUserName() {
        return userName;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setUserName(String userName) {
        this.userName = userName;
    }

    public String getProfileImg() {
        return profileImg;
    }

    public void setProfileImg(String profileImg) {
        this.profileImg = profileImg;
    }

}
