package com.sicoms.smartplug.dao;

import de.greenrobot.dao.DaoException;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table tb_place_setting.
 */
public class DbPlaceSettingVo {

    private Long id;
    /** Not-null value. */
    private String placeId;
    /** Not-null value. */
    private String setId;
    /** Not-null value. */
    private String setVal;

    /** Used to resolve relations */
    private transient DaoSession daoSession;

    /** Used for active entity operations. */
    private transient DbPlaceSettingVoDao myDao;

    private DbPlaceVo dbPlaceVo;
    private String dbPlaceVo__resolvedKey;


    public DbPlaceSettingVo() {
    }

    public DbPlaceSettingVo(Long id) {
        this.id = id;
    }

    public DbPlaceSettingVo(Long id, String placeId, String setId, String setVal) {
        this.id = id;
        this.placeId = placeId;
        this.setId = setId;
        this.setVal = setVal;
    }

    /** called by internal mechanisms, do not call yourself. */
    public void __setDaoSession(DaoSession daoSession) {
        this.daoSession = daoSession;
        myDao = daoSession != null ? daoSession.getDbPlaceSettingVoDao() : null;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    /** Not-null value. */
    public String getPlaceId() {
        return placeId;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setPlaceId(String placeId) {
        this.placeId = placeId;
    }

    /** Not-null value. */
    public String getSetId() {
        return setId;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setSetId(String setId) {
        this.setId = setId;
    }

    /** Not-null value. */
    public String getSetVal() {
        return setVal;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setSetVal(String setVal) {
        this.setVal = setVal;
    }

    /** To-one relationship, resolved on first access. */
    public DbPlaceVo getDbPlaceVo() {
        String __key = this.placeId;
        if (dbPlaceVo__resolvedKey == null || dbPlaceVo__resolvedKey != __key) {
            if (daoSession == null) {
                throw new DaoException("Entity is detached from DAO context");
            }
            DbPlaceVoDao targetDao = daoSession.getDbPlaceVoDao();
            DbPlaceVo dbPlaceVoNew = targetDao.load(__key);
            synchronized (this) {
                dbPlaceVo = dbPlaceVoNew;
            	dbPlaceVo__resolvedKey = __key;
            }
        }
        return dbPlaceVo;
    }

    public void setDbPlaceVo(DbPlaceVo dbPlaceVo) {
        if (dbPlaceVo == null) {
            throw new DaoException("To-one property 'placeId' has not-null constraint; cannot set to-one to null");
        }
        synchronized (this) {
            this.dbPlaceVo = dbPlaceVo;
            placeId = dbPlaceVo.getPlaceId();
            dbPlaceVo__resolvedKey = placeId;
        }
    }

    /** Convenient call for {@link AbstractDao#delete(Object)}. Entity must attached to an entity context. */
    public void delete() {
        if (myDao == null) {
            throw new DaoException("Entity is detached from DAO context");
        }    
        myDao.delete(this);
    }

    /** Convenient call for {@link AbstractDao#update(Object)}. Entity must attached to an entity context. */
    public void update() {
        if (myDao == null) {
            throw new DaoException("Entity is detached from DAO context");
        }    
        myDao.update(this);
    }

    /** Convenient call for {@link AbstractDao#refresh(Object)}. Entity must attached to an entity context. */
    public void refresh() {
        if (myDao == null) {
            throw new DaoException("Entity is detached from DAO context");
        }    
        myDao.refresh(this);
    }

}
