package com.sicoms.smartplug.dao;

import java.util.List;
import java.util.ArrayList;
import android.database.Cursor;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteStatement;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.Property;
import de.greenrobot.dao.internal.SqlUtils;
import de.greenrobot.dao.internal.DaoConfig;
import de.greenrobot.dao.query.Query;
import de.greenrobot.dao.query.QueryBuilder;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table tb_plug.
*/
public class DbPlugVoDao extends AbstractDao<DbPlugVo, String> {

    public static final String TABLENAME = "tb_plug";

    /**
     * Properties of entity DbPlugVo.<br/>
     * Can be used for QueryBuilder and for referencing column names.
    */
    public static class Properties {
        public final static Property PlaceId = new Property(0, String.class, "placeId", false, "PLACE_ID");
        public final static Property PlugId = new Property(1, String.class, "plugId", true, "PLUG_ID");
        public final static Property PlugName = new Property(2, String.class, "plugName", false, "PLUG_NAME");
        public final static Property PlugType = new Property(3, String.class, "plugType", false, "PLUG_TYPE");
        public final static Property PlugImg = new Property(4, String.class, "plugImg", false, "PLUG_IMG");
        public final static Property BssId = new Property(5, String.class, "bssId", false, "BSS_ID");
        public final static Property RouterIp = new Property(6, String.class, "routerIp", false, "ROUTER_IP");
        public final static Property GatewayIp = new Property(7, String.class, "gatewayIp", false, "GATEWAY_IP");
        public final static Property Uuid = new Property(8, String.class, "uuid", false, "UUID");
    }

    private DaoSession daoSession;

    private Query<DbPlugVo> dbPlaceVo_PlugListQuery;

    public DbPlugVoDao(DaoConfig config) {
        super(config);
    }
    
    public DbPlugVoDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
        this.daoSession = daoSession;
    }

    /** Creates the underlying database table. */
    public static void createTable(SQLiteDatabase db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "'tb_plug' (" + //
                "'PLACE_ID' TEXT," + // 0: placeId
                "'PLUG_ID' TEXT PRIMARY KEY NOT NULL ," + // 1: plugId
                "'PLUG_NAME' TEXT NOT NULL ," + // 2: plugName
                "'PLUG_TYPE' TEXT," + // 3: plugType
                "'PLUG_IMG' TEXT," + // 4: plugImg
                "'BSS_ID' TEXT," + // 5: bssId
                "'ROUTER_IP' TEXT," + // 6: routerIp
                "'GATEWAY_IP' TEXT," + // 7: gatewayIp
                "'UUID' TEXT);"); // 8: uuid
        // Add Indexes
        db.execSQL("CREATE UNIQUE INDEX " + constraint + "IDX_tb_plug_PLACE_ID_PLUG_ID ON tb_plug" +
                " (PLACE_ID,PLUG_ID);");
    }

    /** Drops the underlying database table. */
    public static void dropTable(SQLiteDatabase db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "'tb_plug'";
        db.execSQL(sql);
    }

    /** @inheritdoc */
    @Override
    protected void bindValues(SQLiteStatement stmt, DbPlugVo entity) {
        stmt.clearBindings();
 
        String placeId = entity.getPlaceId();
        if (placeId != null) {
            stmt.bindString(1, placeId);
        }
 
        String plugId = entity.getPlugId();
        if (plugId != null) {
            stmt.bindString(2, plugId);
        }
        stmt.bindString(3, entity.getPlugName());
 
        String plugType = entity.getPlugType();
        if (plugType != null) {
            stmt.bindString(4, plugType);
        }
 
        String plugImg = entity.getPlugImg();
        if (plugImg != null) {
            stmt.bindString(5, plugImg);
        }
 
        String bssId = entity.getBssId();
        if (bssId != null) {
            stmt.bindString(6, bssId);
        }
 
        String routerIp = entity.getRouterIp();
        if (routerIp != null) {
            stmt.bindString(7, routerIp);
        }
 
        String gatewayIp = entity.getGatewayIp();
        if (gatewayIp != null) {
            stmt.bindString(8, gatewayIp);
        }
 
        String uuid = entity.getUuid();
        if (uuid != null) {
            stmt.bindString(9, uuid);
        }
    }

    @Override
    protected void attachEntity(DbPlugVo entity) {
        super.attachEntity(entity);
        entity.__setDaoSession(daoSession);
    }

    /** @inheritdoc */
    @Override
    public String readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1);
    }    

    /** @inheritdoc */
    @Override
    public DbPlugVo readEntity(Cursor cursor, int offset) {
        DbPlugVo entity = new DbPlugVo( //
            cursor.isNull(offset + 0) ? null : cursor.getString(offset + 0), // placeId
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1), // plugId
            cursor.getString(offset + 2), // plugName
            cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3), // plugType
            cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4), // plugImg
            cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5), // bssId
            cursor.isNull(offset + 6) ? null : cursor.getString(offset + 6), // routerIp
            cursor.isNull(offset + 7) ? null : cursor.getString(offset + 7), // gatewayIp
            cursor.isNull(offset + 8) ? null : cursor.getString(offset + 8) // uuid
        );
        return entity;
    }
     
    /** @inheritdoc */
    @Override
    public void readEntity(Cursor cursor, DbPlugVo entity, int offset) {
        entity.setPlaceId(cursor.isNull(offset + 0) ? null : cursor.getString(offset + 0));
        entity.setPlugId(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
        entity.setPlugName(cursor.getString(offset + 2));
        entity.setPlugType(cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3));
        entity.setPlugImg(cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4));
        entity.setBssId(cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5));
        entity.setRouterIp(cursor.isNull(offset + 6) ? null : cursor.getString(offset + 6));
        entity.setGatewayIp(cursor.isNull(offset + 7) ? null : cursor.getString(offset + 7));
        entity.setUuid(cursor.isNull(offset + 8) ? null : cursor.getString(offset + 8));
     }
    
    /** @inheritdoc */
    @Override
    protected String updateKeyAfterInsert(DbPlugVo entity, long rowId) {
        return entity.getPlugId();
    }
    
    /** @inheritdoc */
    @Override
    public String getKey(DbPlugVo entity) {
        if(entity != null) {
            return entity.getPlugId();
        } else {
            return null;
        }
    }

    /** @inheritdoc */
    @Override    
    protected boolean isEntityUpdateable() {
        return true;
    }
    
    /** Internal query to resolve the "plugList" to-many relationship of DbPlaceVo. */
    public List<DbPlugVo> _queryDbPlaceVo_PlugList(String placeId) {
        synchronized (this) {
            if (dbPlaceVo_PlugListQuery == null) {
                QueryBuilder<DbPlugVo> queryBuilder = queryBuilder();
                queryBuilder.where(Properties.PlaceId.eq(null));
                dbPlaceVo_PlugListQuery = queryBuilder.build();
            }
        }
        Query<DbPlugVo> query = dbPlaceVo_PlugListQuery.forCurrentThread();
        query.setParameter(0, placeId);
        return query.list();
    }

    private String selectDeep;

    protected String getSelectDeep() {
        if (selectDeep == null) {
            StringBuilder builder = new StringBuilder("SELECT ");
            SqlUtils.appendColumns(builder, "T", getAllColumns());
            builder.append(',');
            SqlUtils.appendColumns(builder, "T0", daoSession.getDbPlaceVoDao().getAllColumns());
            builder.append(',');
            SqlUtils.appendColumns(builder, "T1", daoSession.getDbLastDataVoDao().getAllColumns());
            builder.append(" FROM tb_plug T");
            builder.append(" LEFT JOIN tb_place T0 ON T.'PLACE_ID'=T0.'PLACE_ID'");
            builder.append(" LEFT JOIN tb_last_data T1 ON T.'PLUG_ID'=T1.'PLUG_ID'");
            builder.append(' ');
            selectDeep = builder.toString();
        }
        return selectDeep;
    }
    
    protected DbPlugVo loadCurrentDeep(Cursor cursor, boolean lock) {
        DbPlugVo entity = loadCurrent(cursor, 0, lock);
        int offset = getAllColumns().length;

        DbPlaceVo dbPlaceVo = loadCurrentOther(daoSession.getDbPlaceVoDao(), cursor, offset);
        entity.setDbPlaceVo(dbPlaceVo);
        offset += daoSession.getDbPlaceVoDao().getAllColumns().length;

        DbLastDataVo dbLastDataVo = loadCurrentOther(daoSession.getDbLastDataVoDao(), cursor, offset);
        entity.setDbLastDataVo(dbLastDataVo);

        return entity;    
    }

    public DbPlugVo loadDeep(Long key) {
        assertSinglePk();
        if (key == null) {
            return null;
        }

        StringBuilder builder = new StringBuilder(getSelectDeep());
        builder.append("WHERE ");
        SqlUtils.appendColumnsEqValue(builder, "T", getPkColumns());
        String sql = builder.toString();
        
        String[] keyArray = new String[] { key.toString() };
        Cursor cursor = db.rawQuery(sql, keyArray);
        
        try {
            boolean available = cursor.moveToFirst();
            if (!available) {
                return null;
            } else if (!cursor.isLast()) {
                throw new IllegalStateException("Expected unique result, but count was " + cursor.getCount());
            }
            return loadCurrentDeep(cursor, true);
        } finally {
            cursor.close();
        }
    }
    
    /** Reads all available rows from the given cursor and returns a list of new ImageTO objects. */
    public List<DbPlugVo> loadAllDeepFromCursor(Cursor cursor) {
        int count = cursor.getCount();
        List<DbPlugVo> list = new ArrayList<DbPlugVo>(count);
        
        if (cursor.moveToFirst()) {
            if (identityScope != null) {
                identityScope.lock();
                identityScope.reserveRoom(count);
            }
            try {
                do {
                    list.add(loadCurrentDeep(cursor, false));
                } while (cursor.moveToNext());
            } finally {
                if (identityScope != null) {
                    identityScope.unlock();
                }
            }
        }
        return list;
    }
    
    protected List<DbPlugVo> loadDeepAllAndCloseCursor(Cursor cursor) {
        try {
            return loadAllDeepFromCursor(cursor);
        } finally {
            cursor.close();
        }
    }
    

    /** A raw-style query where you can pass any WHERE clause and arguments. */
    public List<DbPlugVo> queryDeep(String where, String... selectionArg) {
        Cursor cursor = db.rawQuery(getSelectDeep() + where, selectionArg);
        return loadDeepAllAndCloseCursor(cursor);
    }
 
}
