package com.sicoms.smartplug.dao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table tb_setting.
 */
public class DbSettingVo {

    private String setId;
    /** Not-null value. */
    private String setVal;

    public DbSettingVo() {
    }

    public DbSettingVo(String setId) {
        this.setId = setId;
    }

    public DbSettingVo(String setId, String setVal) {
        this.setId = setId;
        this.setVal = setVal;
    }

    public String getSetId() {
        return setId;
    }

    public void setSetId(String setId) {
        this.setId = setId;
    }

    /** Not-null value. */
    public String getSetVal() {
        return setVal;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setSetVal(String setVal) {
        this.setVal = setVal;
    }

}
